default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: XXXXXX
  password: XXXXX
  host: localhost
  enconding: utf8
development:
  <<: *default
  database: challenge_dev
test:
  <<: *default
  database: challenge_test
